import Head from 'next/head'
import Image from 'next/image'

import FeedBackGroup from '../components/FeedBackGroup/FeedBackGroup'
import CommentBox from '../components/CommentBox/CommentBox'
import Layout from '../components/Layout/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FeedBackGroup/>
        <div className="clearfix" style={{minHeight: "50vh"}}>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
          <CommentBox></CommentBox>
        </div>
      </Layout>
    </div>
  )
}
