import Head from 'next/head'
import Image from 'next/image'

import Navbar from  '../components/Navbar'
import FeedBackGroup from '../components/FeedBackGroup/FeedBackGroup'
import CommentBox from '../components/CommentBox/CommentBox'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <div class="clearfix" style={{minHeight: "50vh"}}>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
        <CommentBox></CommentBox>
      </div>
      <FeedBackGroup></FeedBackGroup>
    </div>
  )
}
